name: Launch

on:
  schedule:
  - cron: '22 2 * * *'
  workflow_dispatch:

env:
  API_URL: https://repo.dotclear.watch/

jobs:
  launch:
    name: Launch DA workflow
    runs-on: ubuntu-latest
    steps:
      - name: Parse distant version
        id: distant
        run: |
          echo "Launch plugins update"
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/daread.yml/dispatches \
            -d '{"ref":"master","inputs":{"api_url":"${{ env.API_URL }}","module_type":"plugin"}}'
          echo "Launch themes update"
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/daread.yml/dispatches \
            -d '{"ref":"master","inputs":{"api_url":"${{ env.API_URL }}","module_type":"theme"}}'

      - name: Send Telegram Message Ok
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            __Dotaddict contribution update__
            - Launch update workflows