name: Launch

on:
  schedule:
  - cron: '22 3 * * *'
  workflow_dispatch:

env:
  API_URL: https://demo.jcdenis.fr/

jobs:
  launch:
    name: Launch DA workflow
    runs-on: ubuntu-latest
    steps:
      - name: Parse distant version
        id: distant
        run: |
          echo "Launch updates"
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/dalaunch.yml/dispatches \
            -d '{"inputs":{"api_url":"${{ env.API_URL }}"}}'
